trigger:
  branches:
    include: [main]
  paths:
    include: [docs/*]

pool:
  vmImage: ubuntu-latest

steps:
- checkout: self

- task: UseDotNet@2
  inputs:
    packageType: 'sdk'
    version: '6.x'

- script: |
    dotnet tool update -g docfx
    
    git submodule update --init --recursive
    git submodule update --recursive --remote
    
    dotnet restore src/DNVGL.SolutionPackage.sln
    
    docfx docs/docfx.json
        
    cd docs/_site
    git config user.email "github-actions-bot@dnv.com"
    git config user.name "github actions boot"
    git add .
    git commit -m "Update docs" || echo "No change to commit"
    git push origin HEAD:gh-pages
