trigger:
  branches:
    include: [main]
  paths:
    include: [docs/*]

pool:
  vmImage: ubuntu-latest

variables: 
- group: 'SolutionPackage'

steps:
- checkout: self

- task: UseDotNet@2
  inputs:
    packageType: 'sdk'
    version: '6.0.406'

- script: |
    git submodule update --init --recursive
    git submodule update --recursive --remote
  displayName: Update submodules

- script: |
    echo '{"sdk":{"version": "6.0.406"}}' > global.json
    dotnet restore src/DNVGL.SolutionPackage.sln
    dotnet tool update -g docfx
    docfx docs/docfx.json
  displayName: Generate docs

- script: |
    cd docs/_site
    git fetch
    git add .
    git config user.email "github-actions-bot@dnv.com"
    git config user.name "github actions boot"
    git commit -m "Update docs" || echo "No change to commit"
    git push https://bot:$(GITHUB_REPO)@github.com/veracity-engineering/SolutionPackage.git HEAD:gh-pages
  displayName: Publish gh-pages
